### ISSUE TITLE
Reading from Pathname fails

### ISSUE THREAD

**Issue by mwean** [defunkt/fakefs#220]
I'm trying to do something like this:

```ruby
def test_pathname_can_read_file
  FileUtils.mkdir_p("/path/to")
  path = '/path/to/file.txt'
  File.open(path, 'w') { |f| f.write "Yatta!" }
  pathname = Pathname.new(path)

  assert pathname.read == 'Yatta!'
end
```

This results in `Errno::ENOENT: No such file or directory @ rb_sysopen - /path/to/file.txt`

However, using `File` to read the file works: `File.read(pathname) #=> Yatta!`

The implementation for `#read` is `def read(*args) IO.read(@path, *args) end` which seems to be bypassing the fake filesystem entirely. Is there a reason for this? If not, I was thinking we could just do something like this instead:

```ruby
def read(*args)
  fake_file = FileSystem.find(@path)
  fake_file.content if fake_file
end
```

If that's ok, I'll make a PR for this. Thanks!

**Comment by smtlaissezfaire** [comment]
Closed with 8b2d3f221cee8c123b455eb86ce50a0fa9930684, 7cc6e9b923c7e0c48757f008bd977754cc03b6a5.  See ticket #280
