### ISSUE TITLE
More maintainer

### ISSUE THREAD

**Issue by PierreRambaud** [defunkt/fakefs#274]
Hi,

Just in case if you need more maintainer to manage this repository and all incoming pull request, I will be glad to help you ;)

Regards

**Comment by smtlaissezfaire** [comment]
Yeah, we've been talking about doing an open patch system - something like Rubinius.  For now, we're not but in the future, I'm considering forking and moving the project to my personal repo. @defunkt isn't really active anymore and I don't want to bother him - I'm sure he's busy enough running github!

Closing this one for now, but we should revisit soon.
