### ISSUE TITLE
Many, many tests throwing errors on master. 

### ISSUE THREAD

**Issue by deployable** [defunkt/fakefs#276]
I have a lot of tests failing on master. 

There's 103 errors so I haven't waded through them all bit the majority are due to the method signatures changing in `fileutils.rb` from using `options` to `_options` but none of the subsequent references to `options` have changed to `_options`. 

It appears to be related to this Rubocop commit: https://github.com/defunkt/fakefs/commit/a548517ad11a6c50653ce503954b73921c2a7597

**Comment by PierreRambaud** [comment]
Already fixed in #268, waiting for merging

**Comment by smtlaissezfaire** [comment]
Closing this - it's already fixed
