### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by dtognazzini** [defunkt/fakefs#324]
I'm curious what the release plan is with this gem. I see the last release was 0.6.7 in Feb 2015. I need the fix implemented in https://github.com/defunkt/fakefs/pull/298 which was made in Apr 2015. 

Can we get a new release with these fixes?

Thanks!

**Comment by smtlaissezfaire** [comment]
Yep - good idea.  I haven't really been active on the project recently, but I know it's been a while and lots of pull requests have been merged in.

I just release 0.7.0:

https://rubygems.org/gems/fakefs/versions/0.7.0

Have a good weekend!

**Comment by dtognazzini** [comment]
Awesome, thanks! :+1:
